# Generated by Django 4.0.6 on 2022-07-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_coder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
